### ISSUE TITLE
DataTable - StickyHeader misrended

### ISSUE THREAD

**Issue by touazib** [adminfaces/admin-theme#75]
##### Issue Overview

Header of the datatable is misrended when adding [stickyHeader="true"](https://www.primefaces.org/showcase/ui/data/datatable/sticky.xhtml)

##### Current Behaviour

![2017-06-29 15_34_18-admin starter](https://user-images.githubusercontent.com/15329653/27690072-8ed18fd0-5ce0-11e7-8290-8967cf380a68.png)

##### Expected Behaviour

![2017-06-29 15_36_40-admin starter](https://user-images.githubusercontent.com/15329653/27690164-d3d57bfa-5ce0-11e7-847f-5960f970c364.png)

##### How to reproduce  

car-list.xhtml:
```html
<p:dataTable widgetVar="carsTable" var="c" value="#{carListMB.cars}" rows="50"
                                 rowKey="#{c.id}" lazy="true" paginator="true" stickyHeader="true"
                                 filteredValue="#{carListMB.filteredValue}"
                                 paginatorPosition="bottom" selection="#{carListMB.selectedCars}"
                                 paginatorTemplate="{CurrentPageReport}  {FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink} {RowsPerPageDropdown} {JumpToPageDropdown}"
                                 currentPageReportTemplate="[ {startRecord} to {endRecord} of {totalRecords} ]"
                                 rowsPerPageTemplate="5,10,15,20,30"
                            >
```

##### Additional Information

* Affected version:  1.0.0-RC7
* Browser version: any

**Comment by rmpestano** [comment]
Hi @touazib, thanks for reporting but I couldn't reproduce (tested on firefox (54) and chrome (59) both for linux. 

Can you reproduce at showcase? I've added  stickyHeader to the first datatable here: http://adminfaces-rpestano.rhcloud.com/showcase/pages/components/datatable.xhtml

I've also added it to car datatable in [admin-starter](https://starter-adminfaces.rhcloud.com/admin-starter/car-list.xhtml).

Don't forget to clear browser cache before testing.

**Comment by rmpestano** [comment]
now I can reproduce on admin-starter, on showcase it is ok. I will investigate.

**Comment by rmpestano** [comment]
Hi, just found the cause. It works in showcase because datatable is placed **inside a panel** 

```
<p:panel styleClass="box-info" header="Datatable">
   // datatable here
```
and in admin-starter the datatabe is inside **Bootstrap boxes**:

```
<div class="box box-primary" >
            <div class="box-header with-border">
```
the main issue with bootstrap box is that it sets the container position to **relative** and that will break datatable sticky header. I see two solutions:

1 - Force position to initial in bootstrap boxes:
```
<div class="box box-primary" style="position: inherit">
            <div class="box-header with-border" style="position: inherit">
                 // datatable here
```
2 - Replace the boxes by PrimeFaces panel:
```
<p:panel styleClass="card box-info" header="Datatable">
   // datatable here

```

Note that the _card_ class will add shadows to div as in Bootstrap boxes. Also note that admin panel is very similar to BS boxes;


I hope it helps

**Comment by touazib** [comment]
I replaced the BS boxes by PrimeFaces panel and it works !

Thank you very much for this awesome project :)

**Comment by rmpestano** [comment]
Another issues I found with stickyHeader is on small/mobile devices the table is still broken. It is caused by slideMenu menu (which is activated only on mobile). The only fix I found is to disable slideMenu on the page with datatable with stickyHeader. See [this issue](https://github.com/adminfaces/admin-template/issues/24) for info about disabling slideMenu per page.
